package com.startup.cobranza.operacion.mapper;

import com.startup.cobranza.cliente.entity.Cliente;
import com.startup.cobranza.agencia.entity.Agencia;
import com.startup.cobranza.operacion.entity.BienEmbargado;
import com.startup.cobranza.operacion.dto.BienEmbargadoDTO;
import com.startup.cobranza.operacion.dto.OperacionDTO;
import com.startup.cobranza.operacion.dto.OperacionFormDTO;
import com.startup.cobranza.operacion.entity.Operacion;
import com.startup.cobranza.usuario.entity.Usuario;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public class OperacionMapper {

    public OperacionDTO toDTO(Operacion entity) {
        if (entity == null) return null;
        OperacionDTO dto = OperacionDTO.builder()
                .id(entity.getId())
                .cuenta(entity.getCuenta())
                .numeroOperacion(entity.getNumeroOperacion())
                .montoCapital(entity.getMontoCapital())
                .montoTotal(entity.getMontoTotal())
                .diasMora(entity.getDiasMora())
                .moneda(entity.getMoneda())
                .situacion(entity.getSituacion())
                .estado(entity.getEstado())
                .etapa(entity.getEtapa())
                .observacion(entity.getObservacion())
                .rango(entity.getRango())
                .analista(entity.getAnalista())
                .analistaSenior(entity.getAnalistaSenior())
                .numeroExpediente(entity.getNumeroExpediente())
                .tipoProceso(entity.getTipoProceso())
                .tipoJuzgado(entity.getTipoJuzgado())
                .distritoJudicial(entity.getDistritoJudicial())
                .numeroJuzgado(entity.getNumeroJuzgado())
                .activo(entity.getActivo())
                .fechaCreacion(entity.getFechaCreacion())
                .fechaActualizacion(entity.getFechaActualizacion())
                .trans(entity.getTrans())
                .busquedaBienes(entity.getBusquedaBienes())
                .montoDemandado(entity.getMontoDemandado())
                .escribanoLegal(entity.getEscribanoLegal())
                .codigoExpCautelar(entity.getCodigoExpCautelar())
                .incidente(entity.getIncidente())
                .fechaPresentacion(entity.getFechaPresentacion())
                .fechaInadmisiblePrincipal(entity.getFechaInadmisiblePrincipal())
                .fechaAdmisionPrincipal(entity.getFechaAdmisionPrincipal())
                .fechaAudienciaUnica(entity.getFechaAudienciaUnica())
                .fechaAutoFinal(entity.getFechaAutoFinal())
                .fechaConsentimiento(entity.getFechaConsentimiento())
                .fechaEjecutoriada(entity.getFechaEjecutoriada())
                .fechaIngresoEjecucion(entity.getFechaIngresoEjecucion())
                .fechaTasacion(entity.getFechaTasacion())
                .fechaNombramientoMartillero(entity.getFechaNombramientoMartillero())
                .fechaRemate1(entity.getFechaRemate1())
                .fechaRemate2(entity.getFechaRemate2())
                .fechaRemate3(entity.getFechaRemate3())
                .observacionActos(entity.getObservacionActos())
                .comentario(entity.getComentario())
                .estadoCartera(entity.getEstadoCartera())
                .fechaDesembolso(entity.getFechaDesembolso())
                .importeDesembolso(entity.getImporteDesembolso())
                .etapaProcesalTexto(entity.getEtapaProcesalTexto())
                .actoPendiente(entity.getActoPendiente())
                .fechaUltimoEstadoProceso(entity.getFechaUltimoEstadoProceso())
                .zona(entity.getZona())
                .departamento(entity.getDepartamento())
                .provincia(entity.getProvincia())
                .distrito(entity.getDistrito())
                .direccion(entity.getDireccion())
                .referencia(entity.getReferencia())
                .telefono(entity.getTelefono())
                .montoAprobado(entity.getMontoAprobado())
                .fechaAceptacionDemanda(entity.getFechaAceptacionDemanda())
                .fechaEnvioJudicial(entity.getFechaEnvioJudicial())
                .fechaAsignacionAbogado(entity.getFechaAsignacionAbogado())
                .fechaCastigo(entity.getFechaCastigo())
                .tipoFondo(entity.getTipoFondo())
                .coTitularAval(entity.getCoTitularAval())
                .numeroPartida(entity.getNumeroPartida())
                .numeroFichaRegistral(entity.getNumeroFichaRegistral())
                .build();

        if (entity.getCliente() != null) {
            dto.setClienteId(entity.getCliente().getId());
            dto.setClienteNombre(entity.getCliente().getNombreCompleto());
            dto.setClienteDni(entity.getCliente().getDni());
        }
        if (entity.getAgencia() != null) {
            dto.setAgenciaId(entity.getAgencia().getId());
            dto.setAgenciaNombre(entity.getAgencia().getNombre());
        }
        if (entity.getAbogado() != null) {
            dto.setAbogadoId(entity.getAbogado().getId());
            dto.setAbogadoNombre(entity.getAbogado().getNombreCompleto());
        }
        if (entity.getBienesEmbargados() != null) {
            dto.setBienEmbargados(
                entity.getBienesEmbargados().stream()
                    .map(this::toBienEmbargadoDTO)
                    .toList()
            );
        }
        return dto;
    }

    private BienEmbargadoDTO toBienEmbargadoDTO(BienEmbargado entity) {
        return BienEmbargadoDTO.builder()
                .id(entity.getId())
                .operacionId(entity.getOperacion() != null ? entity.getOperacion().getId() : null)
                .tipoBien(entity.getTipoBien())
                .partidaRegistral(entity.getPartidaRegistral())
                .detalleGarantia(entity.getDetalleGarantia())
                .direccion(entity.getDireccion())
                .distrito(entity.getDistrito())
                .provincia(entity.getProvincia())
                .departamento(entity.getDepartamento())
                .garantiaInscrita(entity.getGarantiaInscrita())
                .fechaInscripcion(entity.getFechaInscripcion())
                .fechaPresentacionRrpp(entity.getFechaPresentacionRrpp())
                .asientoInscripcion(entity.getAsientoInscripcion())
                .montoMc(entity.getMontoMc())
                .monedaMc(entity.getMonedaMc())
                .rango(entity.getRango())
                .detalleAcreedores(entity.getDetalleAcreedores())
                .tipoPreferencia(entity.getTipoPreferencia())
                .titularPredio(entity.getTitularPredio())
                .fechaGeneracionMc(entity.getFechaGeneracionMc())
                .fechaPresentacionMc(entity.getFechaPresentacionMc())
                .fechaInadmisible(entity.getFechaInadmisible())
                .fechaAdmision(entity.getFechaAdmision())
                .comentarioMc(entity.getComentarioMc())
                .build();
    }

    public Operacion toEntity(OperacionDTO dto, Cliente cliente, Agencia agencia, Usuario abogado) {
        if (dto == null) return null;
        return Operacion.builder()
                .id(dto.getId())
                .cliente(cliente)
                .agencia(agencia)
                .cuenta(dto.getCuenta())
                .numeroOperacion(dto.getNumeroOperacion())
                .montoCapital(dto.getMontoCapital())
                .montoTotal(dto.getMontoTotal())
                .diasMora(dto.getDiasMora())
                .moneda(dto.getMoneda())
                .situacion(dto.getSituacion())
                .estado(dto.getEstado())
                .etapa(dto.getEtapa())
                .observacion(dto.getObservacion())
                .rango(dto.getRango())
                .analista(dto.getAnalista())
                .analistaSenior(dto.getAnalistaSenior())
                .numeroExpediente(dto.getNumeroExpediente())
                .tipoProceso(dto.getTipoProceso())
                .tipoJuzgado(dto.getTipoJuzgado())
                .distritoJudicial(dto.getDistritoJudicial())
                .numeroJuzgado(dto.getNumeroJuzgado())
                .abogado(abogado)
                .trans(dto.getTrans())
                .busquedaBienes(dto.getBusquedaBienes())
                .montoDemandado(dto.getMontoDemandado())
                .escribanoLegal(dto.getEscribanoLegal())
                .codigoExpCautelar(dto.getCodigoExpCautelar())
                .incidente(dto.getIncidente())
                .fechaPresentacion(dto.getFechaPresentacion())
                .fechaInadmisiblePrincipal(dto.getFechaInadmisiblePrincipal())
                .fechaAdmisionPrincipal(dto.getFechaAdmisionPrincipal())
                .fechaAudienciaUnica(dto.getFechaAudienciaUnica())
                .fechaAutoFinal(dto.getFechaAutoFinal())
                .fechaConsentimiento(dto.getFechaConsentimiento())
                .fechaEjecutoriada(dto.getFechaEjecutoriada())
                .fechaIngresoEjecucion(dto.getFechaIngresoEjecucion())
                .fechaTasacion(dto.getFechaTasacion())
                .fechaNombramientoMartillero(dto.getFechaNombramientoMartillero())
                .fechaRemate1(dto.getFechaRemate1())
                .fechaRemate2(dto.getFechaRemate2())
                .fechaRemate3(dto.getFechaRemate3())
                .observacionActos(dto.getObservacionActos())
                .comentario(dto.getComentario())
                .estadoCartera(dto.getEstadoCartera())
                .fechaDesembolso(dto.getFechaDesembolso())
                .importeDesembolso(dto.getImporteDesembolso())
                .etapaProcesalTexto(dto.getEtapaProcesalTexto())
                .actoPendiente(dto.getActoPendiente())
                .fechaUltimoEstadoProceso(dto.getFechaUltimoEstadoProceso())
                .zona(dto.getZona())
                .departamento(dto.getDepartamento())
                .provincia(dto.getProvincia())
                .distrito(dto.getDistrito())
                .direccion(dto.getDireccion())
                .referencia(dto.getReferencia())
                .telefono(dto.getTelefono())
                .montoAprobado(dto.getMontoAprobado())
                .fechaAceptacionDemanda(dto.getFechaAceptacionDemanda())
                .fechaEnvioJudicial(dto.getFechaEnvioJudicial())
                .fechaAsignacionAbogado(dto.getFechaAsignacionAbogado())
                .fechaCastigo(dto.getFechaCastigo())
                .tipoFondo(dto.getTipoFondo())
                .coTitularAval(dto.getCoTitularAval())
                .numeroPartida(dto.getNumeroPartida())
                .numeroFichaRegistral(dto.getNumeroFichaRegistral())
                .build();
    }

    public OperacionFormDTO toFormDTO(Operacion entity) {
        if (entity == null) return null;
        return OperacionFormDTO.builder()
                .id(entity.getId())
                .clienteId(entity.getCliente() != null ? entity.getCliente().getId() : null)
                .agenciaId(entity.getAgencia() != null ? entity.getAgencia().getId() : null)
                .cuenta(entity.getCuenta())
                .numeroOperacion(entity.getNumeroOperacion())
                .montoCapital(entity.getMontoCapital())
                .montoTotal(entity.getMontoTotal())
                .diasMora(entity.getDiasMora())
                .moneda(entity.getMoneda())
                .situacion(entity.getSituacion())
                .estado(entity.getEstado())
                .etapa(entity.getEtapa())
                .observacion(entity.getObservacion())
                .rango(entity.getRango())
                .analista(entity.getAnalista())
                .analistaSenior(entity.getAnalistaSenior())
                .numeroExpediente(entity.getNumeroExpediente())
                .tipoProceso(entity.getTipoProceso())
                .tipoJuzgado(entity.getTipoJuzgado())
                .distritoJudicial(entity.getDistritoJudicial())
                .numeroJuzgado(entity.getNumeroJuzgado())
                .abogadoId(entity.getAbogado() != null ? entity.getAbogado().getId() : null)
                .trans(entity.getTrans())
                .busquedaBienes(entity.getBusquedaBienes())
                .escribanoLegal(entity.getEscribanoLegal())
                .codigoExpCautelar(entity.getCodigoExpCautelar())
                .incidente(entity.getIncidente())
                .montoDemandado(entity.getMontoDemandado())
                .fechaPresentacion(entity.getFechaPresentacion() != null ? entity.getFechaPresentacion().toString() : null)
                .fechaInadmisiblePrincipal(entity.getFechaInadmisiblePrincipal() != null ? entity.getFechaInadmisiblePrincipal().toString() : null)
                .fechaAdmisionPrincipal(entity.getFechaAdmisionPrincipal() != null ? entity.getFechaAdmisionPrincipal().toString() : null)
                .fechaAudienciaUnica(entity.getFechaAudienciaUnica() != null ? entity.getFechaAudienciaUnica().toString() : null)
                .fechaAutoFinal(entity.getFechaAutoFinal() != null ? entity.getFechaAutoFinal().toString() : null)
                .fechaConsentimiento(entity.getFechaConsentimiento() != null ? entity.getFechaConsentimiento().toString() : null)
                .fechaEjecutoriada(entity.getFechaEjecutoriada() != null ? entity.getFechaEjecutoriada().toString() : null)
                .fechaIngresoEjecucion(entity.getFechaIngresoEjecucion() != null ? entity.getFechaIngresoEjecucion().toString() : null)
                .fechaTasacion(entity.getFechaTasacion() != null ? entity.getFechaTasacion().toString() : null)
                .fechaNombramientoMartillero(entity.getFechaNombramientoMartillero() != null ? entity.getFechaNombramientoMartillero().toString() : null)
                .fechaRemate1(entity.getFechaRemate1() != null ? entity.getFechaRemate1().toString() : null)
                .fechaRemate2(entity.getFechaRemate2() != null ? entity.getFechaRemate2().toString() : null)
                .fechaRemate3(entity.getFechaRemate3() != null ? entity.getFechaRemate3().toString() : null)
                .observacionActos(entity.getObservacionActos())
                .comentario(entity.getComentario())
                .estadoCartera(entity.getEstadoCartera())
                .fechaDesembolso(entity.getFechaDesembolso() != null ? entity.getFechaDesembolso().toString() : null)
                .importeDesembolso(entity.getImporteDesembolso() != null ? entity.getImporteDesembolso().toString() : null)
                .etapaProcesalTexto(entity.getEtapaProcesalTexto())
                .actoPendiente(entity.getActoPendiente())
                .fechaUltimoEstadoProceso(entity.getFechaUltimoEstadoProceso() != null ? entity.getFechaUltimoEstadoProceso().toString() : null)
                .zona(entity.getZona())
                .departamento(entity.getDepartamento())
                .provincia(entity.getProvincia())
                .distrito(entity.getDistrito())
                .direccion(entity.getDireccion())
                .referencia(entity.getReferencia())
                .telefono(entity.getTelefono())
                .montoAprobado(entity.getMontoAprobado() != null ? entity.getMontoAprobado().toString() : null)
                .fechaAceptacionDemanda(entity.getFechaAceptacionDemanda() != null ? entity.getFechaAceptacionDemanda().toString() : null)
                .fechaEnvioJudicial(entity.getFechaEnvioJudicial() != null ? entity.getFechaEnvioJudicial().toString() : null)
                .fechaAsignacionAbogado(entity.getFechaAsignacionAbogado() != null ? entity.getFechaAsignacionAbogado().toString() : null)
                .fechaCastigo(entity.getFechaCastigo() != null ? entity.getFechaCastigo().toString() : null)
                .tipoFondo(entity.getTipoFondo())
                .coTitularAval(entity.getCoTitularAval())
                .numeroPartida(entity.getNumeroPartida())
                .bienesEmbargados(entity.getBienesEmbargados() != null
                        ? entity.getBienesEmbargados().stream().map(this::toBienEmbargadoDTO).toList()
                        : null)
                .build();
    }

    public Operacion toEntityFromForm(OperacionFormDTO form, Cliente cliente, Agencia agencia, Usuario abogado) {
        if (form == null) return null;
        return Operacion.builder()
                .id(form.getId())
                .cliente(cliente)
                .agencia(agencia)
                .cuenta(form.getCuenta())
                .numeroOperacion(form.getNumeroOperacion())
                .montoCapital(form.getMontoCapital())
                .montoTotal(form.getMontoTotal())
                .diasMora(form.getDiasMora())
                .moneda(form.getMoneda())
                .situacion(form.getSituacion())
                .estado(form.getEstado())
                .etapa(form.getEtapa())
                .observacion(form.getObservacion())
                .rango(form.getRango())
                .analista(form.getAnalista())
                .analistaSenior(form.getAnalistaSenior())
                .numeroExpediente(form.getNumeroExpediente())
                .tipoProceso(form.getTipoProceso())
                .tipoJuzgado(form.getTipoJuzgado())
                .distritoJudicial(form.getDistritoJudicial())
                .numeroJuzgado(form.getNumeroJuzgado())
                .abogado(abogado)
                .trans(form.getTrans())
                .busquedaBienes(form.getBusquedaBienes())
                .escribanoLegal(form.getEscribanoLegal())
                .codigoExpCautelar(form.getCodigoExpCautelar())
                .incidente(form.getIncidente())
                .montoDemandado(form.getMontoDemandado())
                .fechaPresentacion(form.getFechaPresentacion() != null && !form.getFechaPresentacion().isEmpty() ? java.time.LocalDate.parse(form.getFechaPresentacion()) : null)
                .fechaInadmisiblePrincipal(form.getFechaInadmisiblePrincipal() != null && !form.getFechaInadmisiblePrincipal().isEmpty() ? java.time.LocalDate.parse(form.getFechaInadmisiblePrincipal()) : null)
                .fechaAdmisionPrincipal(form.getFechaAdmisionPrincipal() != null && !form.getFechaAdmisionPrincipal().isEmpty() ? java.time.LocalDate.parse(form.getFechaAdmisionPrincipal()) : null)
                .fechaAudienciaUnica(form.getFechaAudienciaUnica() != null && !form.getFechaAudienciaUnica().isEmpty() ? java.time.LocalDate.parse(form.getFechaAudienciaUnica()) : null)
                .fechaAutoFinal(form.getFechaAutoFinal() != null && !form.getFechaAutoFinal().isEmpty() ? java.time.LocalDate.parse(form.getFechaAutoFinal()) : null)
                .fechaConsentimiento(form.getFechaConsentimiento() != null && !form.getFechaConsentimiento().isEmpty() ? java.time.LocalDate.parse(form.getFechaConsentimiento()) : null)
                .fechaEjecutoriada(form.getFechaEjecutoriada() != null && !form.getFechaEjecutoriada().isEmpty() ? java.time.LocalDate.parse(form.getFechaEjecutoriada()) : null)
                .fechaIngresoEjecucion(form.getFechaIngresoEjecucion() != null && !form.getFechaIngresoEjecucion().isEmpty() ? java.time.LocalDate.parse(form.getFechaIngresoEjecucion()) : null)
                .fechaTasacion(form.getFechaTasacion() != null && !form.getFechaTasacion().isEmpty() ? java.time.LocalDate.parse(form.getFechaTasacion()) : null)
                .fechaNombramientoMartillero(form.getFechaNombramientoMartillero() != null && !form.getFechaNombramientoMartillero().isEmpty() ? java.time.LocalDate.parse(form.getFechaNombramientoMartillero()) : null)
                .fechaRemate1(form.getFechaRemate1() != null && !form.getFechaRemate1().isEmpty() ? java.time.LocalDate.parse(form.getFechaRemate1()) : null)
                .fechaRemate2(form.getFechaRemate2() != null && !form.getFechaRemate2().isEmpty() ? java.time.LocalDate.parse(form.getFechaRemate2()) : null)
                .fechaRemate3(form.getFechaRemate3() != null && !form.getFechaRemate3().isEmpty() ? java.time.LocalDate.parse(form.getFechaRemate3()) : null)
                .observacionActos(form.getObservacionActos())
                .comentario(form.getComentario())
                .estadoCartera(form.getEstadoCartera())
                .fechaDesembolso(form.getFechaDesembolso() != null && !form.getFechaDesembolso().isEmpty()
                        ? java.time.LocalDate.parse(form.getFechaDesembolso()) : null)
                .importeDesembolso(form.getImporteDesembolso() != null && !form.getImporteDesembolso().isEmpty()
                        ? new java.math.BigDecimal(form.getImporteDesembolso()) : null)
                .etapaProcesalTexto(form.getEtapaProcesalTexto())
                .actoPendiente(form.getActoPendiente())
                .fechaUltimoEstadoProceso(form.getFechaUltimoEstadoProceso() != null && !form.getFechaUltimoEstadoProceso().isEmpty()
                        ? java.time.LocalDate.parse(form.getFechaUltimoEstadoProceso()) : null)
                .zona(form.getZona())
                .departamento(form.getDepartamento())
                .provincia(form.getProvincia())
                .distrito(form.getDistrito())
                .direccion(form.getDireccion())
                .referencia(form.getReferencia())
                .telefono(form.getTelefono())
                .montoAprobado(form.getMontoAprobado() != null && !form.getMontoAprobado().isEmpty()
                        ? new java.math.BigDecimal(form.getMontoAprobado()) : null)
                .fechaAceptacionDemanda(form.getFechaAceptacionDemanda() != null && !form.getFechaAceptacionDemanda().isEmpty()
                        ? java.time.LocalDate.parse(form.getFechaAceptacionDemanda()) : null)
                .fechaEnvioJudicial(form.getFechaEnvioJudicial() != null && !form.getFechaEnvioJudicial().isEmpty()
                        ? java.time.LocalDate.parse(form.getFechaEnvioJudicial()) : null)
                .fechaAsignacionAbogado(form.getFechaAsignacionAbogado() != null && !form.getFechaAsignacionAbogado().isEmpty()
                        ? java.time.LocalDate.parse(form.getFechaAsignacionAbogado()) : null)
                .fechaCastigo(form.getFechaCastigo() != null && !form.getFechaCastigo().isEmpty()
                        ? java.time.LocalDate.parse(form.getFechaCastigo()) : null)
                .tipoFondo(form.getTipoFondo())
                .coTitularAval(form.getCoTitularAval())
                .numeroPartida(form.getNumeroPartida())
                .build();
    }
}
